# Generated by Django 4.2.30 on 2026-05-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='propiedades.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evidencias/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='inspecciones.inspeccion')),
            ],
        ),
    ]
