# Generated by Django 4.2.30 on 2026-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash SHA-256'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tsa_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp TSA'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tsa_token',
            field=models.BinaryField(blank=True, null=True, verbose_name='Token TSA (.tsr)'),
        ),
    ]
