# Generated by Django 4.2.30 on 2026-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la propiedad')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
